Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,4 +19,6 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Run a simple command
-        run: echo "Hello, this is a simple CI pipeline!" error
+        run: |
+          set -e
+          echo "Hello, this is a simple CI pipeline!" error
